# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TagAlong' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'

  # Pods for TagAlong

  target 'TagAlongTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TagAlongUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
